# Generated by Django 4.2.5 on 2023-10-02 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wbt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='google_maps',
            field=models.CharField(max_length=1500),
        ),
    ]
